/**
 * Synthetic demo personas for RediWala development.
 * Passwords are used only by the Admin seeding tool — never written to RTDB.
 */

export const DEMO_CUSTOMERS = Object.freeze([
  {
    key: "meena",
    email: "meena@demo.rediwala",
    password: "Meena123!",
    displayName: "Meena Krishnan",
    preferredLanguage: "en",
    secondaryLanguage: "ta",
    homeNeighborhood: "west_mambalam",
    homeAreaLabel: "Postal Colony, West Mambalam, Chennai",
    homeCoordinate: { latitude: 13.0386, longitude: 80.2208 },
    apartmentMetadata: null,
    todaysNeeds: ["vegetables", "flowers", "ironing"],
    followedVendorIds: ["murugan", "lakshmi", "siva_ironing"],
    savedVendorIds: ["babu_laundry"],
    persona: "Homemaker who regularly buys vegetables and flowers and sends clothing for ironing.",
  },
  {
    key: "sundaram",
    email: "sundaram@demo.rediwala",
    password: "Sundaram123!",
    displayName: "Sundaram Iyer",
    preferredLanguage: "ta",
    secondaryLanguage: "en",
    homeNeighborhood: "west_mambalam",
    homeAreaLabel: "Lake View Road, West Mambalam, Chennai",
    homeCoordinate: { latitude: 13.0374, longitude: 80.2226 },
    apartmentMetadata: null,
    todaysNeeds: ["cableBill", "laundryPickup", "bananas"],
    followedVendorIds: ["kumar_cable", "babu_laundry"],
    savedVendorIds: [],
    persona: "Retired customer tracking neighborhood service arrivals.",
  },
  {
    key: "priya",
    email: "priya@demo.rediwala",
    password: "Priya123!",
    displayName: "Priya Narayanan",
    preferredLanguage: "en",
    secondaryLanguage: null,
    homeNeighborhood: "thiruvanmiyur",
    homeAreaLabel: "Kannappa Nagar, Thiruvanmiyur, Chennai",
    homeCoordinate: { latitude: 12.9862, longitude: 80.2588 },
    apartmentMetadata: null,
    todaysNeeds: ["freshFish", "fruits", "knifeSharpening"],
    followedVendorIds: [],
    savedVendorIds: ["valli_fruit"],
    persona: "Busy professional open to any reliable nearby match.",
  },
  {
    key: "lakshmi_home",
    email: "lakshmi.home@demo.rediwala",
    password: "Lakshmi123!",
    displayName: "Lakshmi Household",
    preferredLanguage: "ta",
    secondaryLanguage: "en",
    homeNeighborhood: "thiruvanmiyur",
    homeAreaLabel: "Kurinji Nagar, Thiruvanmiyur, Chennai",
    homeCoordinate: { latitude: 12.9844, longitude: 80.2572 },
    apartmentMetadata: null,
    todaysNeeds: ["waterCan", "ironing", "vegetables"],
    followedVendorIds: ["babu_laundry", "siva_ironing"],
    savedVendorIds: [],
    persona: "Shared household account for family or household staff.",
  },
  {
    key: "ravi",
    email: "ravi.apartment@demo.rediwala",
    password: "Ravi123!",
    displayName: "Ravi Apartments",
    preferredLanguage: "en",
    secondaryLanguage: null,
    homeNeighborhood: "thiruvanmiyur",
    homeAreaLabel: "Seashore Apartments, Thiruvanmiyur, Chennai",
    homeCoordinate: { latitude: 12.9836, longitude: 80.2604 },
    apartmentMetadata: {
      name: "Seashore Apartments",
      tower: "Tower A",
      floor: "4",
      serviceEntrance: "East Gate",
    },
    todaysNeeds: ["laundryPickup", "tailor", "flowers"],
    followedVendorIds: ["babu_laundry", "lakshmi"],
    savedVendorIds: [],
    persona: "Apartment resident tracking vendors between blocks.",
  },
]);

export const DEMO_VENDORS = Object.freeze([
  {
    key: "murugan",
    email: "murugan@demo.rediwala",
    password: "Murugan123!",
    vendorId: "murugan",
    businessName: "Murugan Fresh Vegetables",
    businessType: "vegetables",
    serviceMode: "mobile",
    primaryArea: "west_mambalam",
    primaryAreaLabel: "Postal Colony, West Mambalam",
    coordinate: { latitude: 13.0386, longitude: 80.2208 },
    announcement: "Fresh tomatoes, beans, brinjal and greens available today.",
    workingHours: "6:00 AM – 1:00 PM",
    reliability: 0.92,
    presencePolicy: { confirmationRequired: false, intervalMinutes: 120 },
    initialStatus: "live",
    route: [
      { id: "m1", title: "Postal Colony 1st Street", latitude: 13.0389, longitude: 80.2202 },
      { id: "m2", title: "Postal Colony 2nd Street", latitude: 13.0382, longitude: 80.2211 },
      { id: "m3", title: "Lake View Road", latitude: 13.0374, longitude: 80.2226 },
      { id: "m4", title: "Arya Gowda Road", latitude: 13.0368, longitude: 80.2238 },
      { id: "m5", title: "Station Road", latitude: 13.0379, longitude: 80.2251 },
    ],
  },
  {
    key: "lakshmi_flowers",
    email: "lakshmi.flowers@demo.rediwala",
    password: "Flowers123!",
    vendorId: "lakshmi",
    businessName: "Lakshmi Flowers and Garlands",
    businessType: "flowers",
    serviceMode: "stationary",
    primaryArea: "west_mambalam",
    primaryAreaLabel: "Arya Gowda Road, West Mambalam",
    coordinate: { latitude: 13.0368, longitude: 80.2238 },
    announcement: "Jasmine, roses and temple garlands available until noon.",
    workingHours: "6:30 AM – 12:00 PM",
    reliability: 0.9,
    presencePolicy: { confirmationRequired: true, intervalMinutes: 60 },
    initialStatus: "live",
    sessionDurationMinutes: 90,
  },
  {
    key: "siva_ironing",
    email: "siva.ironing@demo.rediwala",
    password: "Ironing123!",
    vendorId: "siva_ironing",
    businessName: "Siva Ironing and Clothing Repairs",
    businessType: "ironing",
    serviceMode: "stationary",
    primaryArea: "thiruvanmiyur",
    primaryAreaLabel: "Kannappa Nagar street corner, Thiruvanmiyur",
    coordinate: { latitude: 12.9862, longitude: 80.2588 },
    announcement: "Ironing and small clothing repairs available this afternoon.",
    workingHours: "10:00 AM – 6:00 PM",
    reliability: 0.88,
    presencePolicy: { confirmationRequired: true, intervalMinutes: 60 },
    initialStatus: "expiring_soon",
    sessionDurationMinutes: 60,
    presenceDueInMinutes: 10,
  },
  {
    key: "babu_laundry",
    email: "babu.laundry@demo.rediwala",
    password: "Laundry123!",
    vendorId: "babu_laundry",
    businessName: "Babu Laundry Pickup",
    businessType: "laundry",
    serviceMode: "mobile",
    primaryArea: "thiruvanmiyur",
    primaryAreaLabel: "Kurinji Nagar and nearby Thiruvanmiyur apartments",
    coordinate: { latitude: 12.9848, longitude: 80.2596 },
    announcement: "Laundry pickup available today. Please keep bags ready at the service entrance.",
    workingHours: "8:00 AM – 5:00 PM",
    reliability: 0.91,
    presencePolicy: { confirmationRequired: false, intervalMinutes: 120 },
    initialStatus: "live",
    currentStop: "Seashore Apartments, Tower C",
    nextStop: "Seashore Apartments, Tower A",
    route: [
      { id: "b1", title: "Kurinji Enclave, Block A", latitude: 12.9844, longitude: 80.2572 },
      { id: "b2", title: "Kurinji Enclave, Block B", latitude: 12.9841, longitude: 80.2579 },
      { id: "b3", title: "Seashore Apartments, Tower C", latitude: 12.9838, longitude: 80.2601 },
      { id: "b4", title: "Seashore Apartments, Tower A", latitude: 12.9836, longitude: 80.2604 },
      { id: "b5", title: "Kannappa Residency", latitude: 12.9860, longitude: 80.2585 },
    ],
  },
  {
    key: "kumar_cable",
    email: "kumar.cable@demo.rediwala",
    password: "Cable123!",
    vendorId: "kumar_cable",
    businessName: "Kumar Cable Collection Service",
    businessType: "cableBill",
    serviceMode: "scheduled",
    primaryArea: "west_mambalam",
    primaryAreaLabel: "West Mambalam",
    coordinate: { latitude: 13.0379, longitude: 80.2251 },
    announcement: "Monthly cable subscription collection round this afternoon.",
    workingHours: "2:00 PM – 5:00 PM",
    reliability: 0.86,
    presencePolicy: { confirmationRequired: true, intervalMinutes: 120 },
    initialStatus: "expected_soon",
    affiliations: ["SVC", "Vanitham Vision"],
    scheduledWindow: { startHour: 14, endHour: 17 },
    route: [
      { id: "k1", title: "Station Road", latitude: 13.0379, longitude: 80.2251 },
      { id: "k2", title: "Postal Colony", latitude: 13.0386, longitude: 80.2208 },
      { id: "k3", title: "Lake View Road", latitude: 13.0374, longitude: 80.2226 },
      { id: "k4", title: "Arya Gowda Road", latitude: 13.0368, longitude: 80.2238 },
    ],
  },
]);

/** Supporting vendors without Auth accounts — keep inside neighborhood clusters. */
export const SUPPORTING_VENDORS = Object.freeze([
  { vendorId: "raja_banana", businessName: "Raja Banana Cart", businessType: "fruits", serviceMode: "mobile", primaryArea: "west_mambalam", coordinate: { latitude: 13.0381, longitude: 80.2215 }, announcement: "Ripe bananas and plantains.", reliability: 0.84, initialStatus: "live" },
  { vendorId: "selvi_greens", businessName: "Selvi Greens", businessType: "vegetables", serviceMode: "mobile", primaryArea: "west_mambalam", coordinate: { latitude: 13.0372, longitude: 80.2210 }, announcement: "Fresh greens and coriander.", reliability: 0.83, initialStatus: "live" },
  { vendorId: "anand_water", businessName: "Anand Water Cans", businessType: "waterCan", serviceMode: "mobile", primaryArea: "west_mambalam", coordinate: { latitude: 13.0365, longitude: 80.2220 }, announcement: "20L water can delivery.", reliability: 0.87, initialStatus: "expected_soon" },
  { vendorId: "mani_knife", businessName: "Mani Knife Sharpening", businessType: "knifeSharpening", serviceMode: "stationary", primaryArea: "west_mambalam", coordinate: { latitude: 13.0370, longitude: 80.2242 }, announcement: "Knife and scissors sharpening.", reliability: 0.8, initialStatus: "live" },
  { vendorId: "shankar_tailor", businessName: "Shankar Tailoring Corner", businessType: "tailor", serviceMode: "stationary", primaryArea: "west_mambalam", coordinate: { latitude: 13.0384, longitude: 80.2230 }, announcement: "Quick alterations and hemming.", reliability: 0.85, initialStatus: "offline" },
  { vendorId: "devi_milk", businessName: "Devi Milk Delivery", businessType: "milk", serviceMode: "mobile", primaryArea: "west_mambalam", coordinate: { latitude: 13.0391, longitude: 80.2218 }, announcement: "Morning milk delivery round.", reliability: 0.89, initialStatus: "expected_soon" },
  { vendorId: "kannan_newspaper", businessName: "Kannan Newspaper Buyer", businessType: "oldNewspapers", serviceMode: "mobile", primaryArea: "west_mambalam", coordinate: { latitude: 13.0362, longitude: 80.2214 }, announcement: "Buying old newspapers today.", reliability: 0.78, initialStatus: "live" },
  { vendorId: "rahim_fish", businessName: "Rahim Fresh Fish", businessType: "fish", serviceMode: "mobile", primaryArea: "thiruvanmiyur", coordinate: { latitude: 12.9855, longitude: 80.2595 }, announcement: "Fresh catch from the market.", reliability: 0.88, initialStatus: "live" },
  { vendorId: "valli_fruit", businessName: "Valli Fruit Cart", businessType: "fruits", serviceMode: "mobile", primaryArea: "thiruvanmiyur", coordinate: { latitude: 12.9868, longitude: 80.2578 }, announcement: "Seasonal fruits and guava.", reliability: 0.86, initialStatus: "live" },
  { vendorId: "chennai_coconut", businessName: "Chennai Tender Coconut", businessType: "tenderCoconut", serviceMode: "stationary", primaryArea: "thiruvanmiyur", coordinate: { latitude: 12.9872, longitude: 80.2608 }, announcement: "Chilled tender coconuts.", reliability: 0.9, initialStatus: "live" },
  { vendorId: "noor_flower", businessName: "Noor Flower Stall", businessType: "flowers", serviceMode: "stationary", primaryArea: "thiruvanmiyur", coordinate: { latitude: 12.9849, longitude: 80.2582 }, announcement: "Fresh jasmine strings.", reliability: 0.84, initialStatus: "live" },
  { vendorId: "gopal_cobbler", businessName: "Gopal Cobbler", businessType: "cobbler", serviceMode: "stationary", primaryArea: "thiruvanmiyur", coordinate: { latitude: 12.9858, longitude: 80.2570 }, announcement: "Shoe repair and polish.", reliability: 0.81, initialStatus: "offline" },
  { vendorId: "ramesh_water", businessName: "Ramesh Water Delivery", businessType: "waterCan", serviceMode: "mobile", primaryArea: "thiruvanmiyur", coordinate: { latitude: 12.9839, longitude: 80.2589 }, announcement: "Apartment water can delivery.", reliability: 0.87, initialStatus: "expected_soon" },
  { vendorId: "kumar_scrap", businessName: "Kumar Scrap Collection", businessType: "metalScrap", serviceMode: "mobile", primaryArea: "thiruvanmiyur", coordinate: { latitude: 12.9846, longitude: 80.2565 }, announcement: "Scrap and metal pickup.", reliability: 0.79, initialStatus: "offline" },
  { vendorId: "ammu_snacks", businessName: "Ammu Evening Snacks", businessType: "foodTruck", serviceMode: "stationary", primaryArea: "thiruvanmiyur", coordinate: { latitude: 12.9865, longitude: 80.2612 }, announcement: "Bajji and tea until evening.", reliability: 0.82, initialStatus: "live" },
  { vendorId: "farida_juice", businessName: "Farida Juice Cart", businessType: "foodTruck", serviceMode: "mobile", primaryArea: "west_mambalam", coordinate: { latitude: 13.0395, longitude: 80.2240 }, announcement: "Fresh sugarcane juice.", reliability: 0.8, initialStatus: "live" },
  { vendorId: "velu_sofa", businessName: "Velu Sofa Repair", businessType: "sofaRepair", serviceMode: "scheduled", primaryArea: "west_mambalam", coordinate: { latitude: 13.0358, longitude: 80.2205 }, announcement: "Sofa and cushion repair visits.", reliability: 0.77, initialStatus: "expected_soon" },
  { vendorId: "rani_ironing", businessName: "Rani Pressing Point", businessType: "ironing", serviceMode: "stationary", primaryArea: "thiruvanmiyur", coordinate: { latitude: 12.9829, longitude: 80.2576 }, announcement: "Same-day ironing stack.", reliability: 0.83, initialStatus: "offline" },
  { vendorId: "joseph_electrical", businessName: "Joseph Electrical Repair", businessType: "electricalRepair", serviceMode: "mobile", primaryArea: "west_mambalam", coordinate: { latitude: 13.0402, longitude: 80.2228 }, announcement: "Fan and switchboard repair.", reliability: 0.85, initialStatus: "expected_soon" },
  { vendorId: "maya_kulfi", businessName: "Maya Kulfi Cycle", businessType: "kulfi", serviceMode: "mobile", primaryArea: "thiruvanmiyur", coordinate: { latitude: 12.9878, longitude: 80.2590 }, announcement: "Malai kulfi and ice cream.", reliability: 0.86, initialStatus: "live" },
]);
